"""remove log stuff for now

Revision ID: 01c3a4b86943
Revises: 4cb3aec1afcd
Create Date: 2025-06-03 22:58:44.366901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01c3a4b86943'
down_revision: Union[str, None] = '4cb3aec1afcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loggable_entity')
    op.drop_table('loggable_entities')
    op.drop_table('log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('success', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('loggable_entities',
    sa.Column('log_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], name=op.f('loggable_entities_ibfk_1')),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('loggable_entity',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('entity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
