"""More of small improvements

Revision ID: 0352cf6ef74c
Revises: 3687e2483334
Create Date: 2025-06-03 16:58:02.841795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0352cf6ef74c'
down_revision: Union[str, None] = '3687e2483334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('employee_privileges', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('employee_privileges_ibfk_1'), 'employee_privileges', type_='foreignkey')
    op.create_foreign_key(None, 'employee_privileges', 'user', ['user_id'], ['id'])
    op.drop_column('employee_privileges', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_privileges', sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee_privileges', type_='foreignkey')
    op.create_foreign_key(op.f('employee_privileges_ibfk_1'), 'employee_privileges', 'employee', ['employee_id'], ['id'])
    op.drop_column('employee_privileges', 'user_id')
    op.drop_column('employee', 'comment')
    # ### end Alembic commands ###
