"""12

Revision ID: 161b13f2e8e5
Revises: 01c3a4b86943
Create Date: 2025-06-05 03:01:56.006987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161b13f2e8e5'
down_revision: Union[str, None] = '01c3a4b86943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_privileges_ibfk_2'), 'user_privileges', type_='foreignkey')
    op.drop_constraint(op.f('user_privileges_ibfk_1'), 'user_privileges', type_='foreignkey')
    op.create_foreign_key(None, 'user_privileges', 'privilege', ['privilege_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_privileges', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_privileges', type_='foreignkey')
    op.drop_constraint(None, 'user_privileges', type_='foreignkey')
    op.create_foreign_key(op.f('user_privileges_ibfk_1'), 'user_privileges', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_privileges_ibfk_2'), 'user_privileges', 'privilege', ['privilege_id'], ['id'])
    # ### end Alembic commands ###
