"""ondelete/onupdate for exercise-exercise_type relation

Revision ID: 24c99df29c25
Revises: e633f664d353
Create Date: 2025-06-11 13:41:38.374287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c99df29c25'
down_revision: Union[str, None] = 'e633f664d353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercise_ibfk_2'), 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'exercisetype', ['exercise_type_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_ibfk_2'), 'exercise', 'exercisetype', ['exercise_type_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
