"""added primary_key=true to some foreginkeys

Revision ID: 2e7ea553e82f
Revises: cba6c862ee87
Create Date: 2025-06-05 08:35:25.411953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e7ea553e82f'
down_revision: Union[str, None] = 'cba6c862ee87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'position_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('employee', 'rang_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('exercise', 'exercise_type_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'exercise_type_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('employee', 'rang_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('employee', 'position_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
