"""Fixed Employee_priv to User_priv

Revision ID: 30de914bcc07
Revises: dd28e6e32063
Create Date: 2025-06-03 19:50:34.114159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30de914bcc07'
down_revision: Union[str, None] = 'dd28e6e32063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_privilege')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_privilege',
    sa.Column('privilege_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['privilege_id'], ['privilege.id'], name=op.f('user_privilege_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_privilege_ibfk_3')),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
