"""removed all mentions of token and other small improvments

Revision ID: 3687e2483334
Revises: fdfce43d9e1f
Create Date: 2025-06-03 16:45:20.237271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3687e2483334'
down_revision: Union[str, None] = 'fdfce43d9e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authenticationtokens')
    op.drop_index(op.f('email'), table_name='userauthentication')
    op.drop_table('userauthentication')
    op.add_column('employee', sa.Column('rang_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('employee_ibfk_1'), 'employee', type_='foreignkey')
    op.drop_constraint(op.f('employee_ibfk_2'), 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'rang', ['rang_id'], ['id'])
    op.create_foreign_key(None, 'employee', 'position', ['position_id'], ['id'])
    op.drop_column('employee', 'rank_id')
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_table('dolzhnost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created')
    op.add_column('employee', sa.Column('rank_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key(op.f('employee_ibfk_2'), 'employee', 'rang', ['rank_id'], ['id'])
    op.create_foreign_key(op.f('employee_ibfk_1'), 'employee', 'dolzhnost', ['position_id'], ['id'])
    op.drop_column('employee', 'rang_id')
    op.create_table('userauthentication',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'userauthentication', ['email'], unique=True)
    op.create_table('authenticationtokens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userauthentication.id'], name=op.f('authenticationtokens_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dolzhnost',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('group_position', mysql.ENUM('среднего и старшего начальствующего состава', 'рядового и младшего начальствующего состава', 'работников'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
