"""removed prepatory period from rang

Revision ID: 53b7d0740405
Revises: 
Create Date: 2025-06-12 18:36:41.117740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53b7d0740405'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rang', 'preparatory_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rang', sa.Column('preparatory_period', mysql.TIME(), nullable=False))
    # ### end Alembic commands ###
