"""ondelete/onupdate for excercise-excercieReport

Revision ID: 65b7b1d7b541
Revises: 24c99df29c25
Create Date: 2025-06-11 13:53:52.849428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b7b1d7b541'
down_revision: Union[str, None] = '24c99df29c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercisesreport_ibfk_1'), 'exercisesreport', type_='foreignkey')
    op.create_foreign_key(None, 'exercisesreport', 'exercise', ['exercise_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercisesreport', type_='foreignkey')
    op.create_foreign_key(op.f('exercisesreport_ibfk_1'), 'exercisesreport', 'exercise', ['exercise_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
