"""Try 1 on making relations indentifying

Revision ID: 74768b683283
Revises: acc6800cc2c8
Create Date: 2025-06-05 05:54:51.941022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '74768b683283'
down_revision: Union[str, None] = 'acc6800cc2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attestation', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('exercise', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('exercisesreport', 'exercise_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('exercisesreport', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercisesreport', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('exercisesreport', 'exercise_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('exercise', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('attestation', 'employee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
