"""user_priv ondelete restrict

Revision ID: 8788466a4a3a
Revises: cfcef6ba8dac
Create Date: 2025-06-05 10:50:46.573243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8788466a4a3a'
down_revision: Union[str, None] = 'cfcef6ba8dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_privileges_ibfk_2'), 'user_privileges', type_='foreignkey')
    op.drop_constraint(op.f('user_privileges_ibfk_3'), 'user_privileges', type_='foreignkey')
    op.create_foreign_key(None, 'user_privileges', 'privilege', ['privilege_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'user_privileges', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_privileges', type_='foreignkey')
    op.drop_constraint(None, 'user_privileges', type_='foreignkey')
    op.create_foreign_key(op.f('user_privileges_ibfk_3'), 'user_privileges', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('user_privileges_ibfk_2'), 'user_privileges', 'privilege', ['privilege_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
