"""added test column to Rang table

Revision ID: a5b45da38d44
Revises: 88cb5b16c71d
Create Date: 2025-06-01 23:11:46.191209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b45da38d44'
down_revision: Union[str, None] = '88cb5b16c71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rang', sa.Column('test', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rang', 'test')
    # ### end Alembic commands ###
