"""employee - exercise report onupdate and ondelete actions

Revision ID: a5fdbd8f954a
Revises: 55b34af52a94
Create Date: 2025-06-11 13:22:14.984968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5fdbd8f954a'
down_revision: Union[str, None] = '55b34af52a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercisesreport_ibfk_2'), 'exercisesreport', type_='foreignkey')
    op.create_foreign_key(None, 'exercisesreport', 'employee', ['employee_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercisesreport', type_='foreignkey')
    op.create_foreign_key(op.f('exercisesreport_ibfk_2'), 'exercisesreport', 'employee', ['employee_id'], ['id'])
    # ### end Alembic commands ###
