"""Added autoincrement and other minor db changes

Revision ID: acc6800cc2c8
Revises: 161b13f2e8e5
Create Date: 2025-06-05 03:41:10.962521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'acc6800cc2c8'
down_revision: Union[str, None] = '161b13f2e8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['login'])
    op.drop_column('user', 'token')
    op.alter_column('user_privileges', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_privileges', 'privilege_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('user_privileges_ibfk_1'), 'user_privileges', type_='foreignkey')
    op.drop_constraint(op.f('user_privileges_ibfk_2'), 'user_privileges', type_='foreignkey')
    op.create_foreign_key(None, 'user_privileges', 'privilege', ['privilege_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_privileges', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_privileges', type_='foreignkey')
    op.drop_constraint(None, 'user_privileges', type_='foreignkey')
    op.create_foreign_key(op.f('user_privileges_ibfk_2'), 'user_privileges', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_privileges_ibfk_1'), 'user_privileges', 'privilege', ['privilege_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_privileges', 'privilege_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_privileges', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
