"""position ondelete restrict

Revision ID: b6a7017b1ec1
Revises: 8788466a4a3a
Create Date: 2025-06-05 11:03:01.971670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a7017b1ec1'
down_revision: Union[str, None] = '8788466a4a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employee_ibfk_1'), 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'position', ['position_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key(op.f('employee_ibfk_1'), 'employee', 'position', ['position_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
