"""Attestation type_id is now primary key

Revision ID: cba6c862ee87
Revises: 3e08bd2fcc80
Create Date: 2025-06-05 08:26:25.256686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cba6c862ee87'
down_revision: Union[str, None] = '3e08bd2fcc80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attestation', 'type_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attestation', 'type_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
