"""user_priv ondelete=restrict

Revision ID: cfcef6ba8dac
Revises: 2e7ea553e82f
Create Date: 2025-06-05 10:48:10.521182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfcef6ba8dac'
down_revision: Union[str, None] = '2e7ea553e82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'login',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_constraint(op.f('user_privileges_ibfk_1'), 'user_privileges', type_='foreignkey')
    op.create_foreign_key(None, 'user_privileges', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_privileges', type_='foreignkey')
    op.create_foreign_key(op.f('user_privileges_ibfk_1'), 'user_privileges', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'login',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
