"""Renamed exercise to PendingExersise

Revision ID: e2f41aed093e
Revises: b6a7017b1ec1
Create Date: 2025-06-06 09:21:50.190623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f41aed093e'
down_revision: Union[str, None] = 'b6a7017b1ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employee_ibfk_2'), 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'rang', ['rang_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key(op.f('employee_ibfk_2'), 'employee', 'rang', ['rang_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
