"""removed employe-exercise report relation

Revision ID: e633f664d353
Revises: a5fdbd8f954a
Create Date: 2025-06-11 13:34:11.872815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e633f664d353'
down_revision: Union[str, None] = 'a5fdbd8f954a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attestation_ibfk_2'), 'attestation', type_='foreignkey')
    op.drop_constraint(op.f('attestation_ibfk_1'), 'attestation', type_='foreignkey')
    op.create_foreign_key(None, 'attestation', 'attestationtype', ['type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'attestation', 'employee', ['employee_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('exercise_ibfk_1'), 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'employee', ['employee_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('exercisesreport_ibfk_2'), 'exercisesreport', type_='foreignkey')
    op.drop_column('exercisesreport', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercisesreport', sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('exercisesreport_ibfk_2'), 'exercisesreport', 'employee', ['employee_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_ibfk_1'), 'exercise', 'employee', ['employee_id'], ['id'])
    op.drop_constraint(None, 'attestation', type_='foreignkey')
    op.drop_constraint(None, 'attestation', type_='foreignkey')
    op.create_foreign_key(op.f('attestation_ibfk_1'), 'attestation', 'employee', ['employee_id'], ['id'])
    op.create_foreign_key(op.f('attestation_ibfk_2'), 'attestation', 'attestationtype', ['type_id'], ['id'])
    # ### end Alembic commands ###
