"""removed test column from rang table

Revision ID: fdfce43d9e1f
Revises: 7a05ddc02645
Create Date: 2025-06-01 23:38:36.958574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fdfce43d9e1f'
down_revision: Union[str, None] = '7a05ddc02645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rang', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rang', sa.Column('test', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
