services:
  # python, fastapi, uvicorn
  web:
    build: .
    command: sh -c "uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000

  # mysql service
  db:
      container_name: mydb
      restart: always
      image: mysql:5.7
      ports:
          - "32001:3306"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: project_db
